package(default_visibility = ["//visibility:public"])

# A new constraint setting and constraint value for this non-standard
# toolchain.
constraint_setting(name = "nonstandard_toolchain")
constraint_value(
    name               = "simple_cpp_toolchain",
    constraint_setting = ":nonstandard_toolchain"
)
